### ISSUE TITLE
JS SDK Should Auto-Convert camelCase to snake_case for Function Names

### ISSUE THREAD

**Issue by idea404** [near/near-sdk-js#136]
**Introduction**

During last DevRel working session, Benji pointed out that the names inconsistencies between JS and Rust for functions will lead to inconsistent naming for logic that is performed on chain. 

e.g.: 
`nft_mint` for a Rust contract vs. `nftMint` for a JS contract

**Problem** 

dApps that listen to data on-chain searching for specific function names will miss data. Some dApps might be built foundationally on the assumption of this being consistent. 

**Solution**

JS SDK auto-converts naming for view and call methods from camelCase or whatever case to snake_case to keep consistency with existing function naming for the ecosystem.

**Comment by idea404** [comment]
This issue was created to start the conversation, topic merits a broader discussion!
Mentioned in discussion: https://github.com/near/near-sdk-js/discussions/138

**Comment by gagdiez** [comment]
In my humble opinion, adding an auto-convert from camelCase to snake_case will add an extra layer of complexity in near-sdk-js. Because of this, I think we should **not** add it. However, I **do agree** that we should standardize always using snake_case in all our examples, and be clear with the community on why we recommend doing so.

**Comment by maxhr** [comment]
I suggest the compiler to wasm to emit a warning, and not do auto-conversions.

**Comment by ailisp** [comment]
auto convert isn't hard to implement, but @gagdiez and @maxhr suggested ways are more robust and no hidden magic would cause user confusion. I think it's a good idea to do they proposed

**Comment by volovyks** [comment]
After additional discussions, we came up with a decision on this:
- No magic, no autoconversion from `camelCase` to `snake_case`
- All standards (FT, NFT, etc.) will use `snake_case`
- All other examples can use `camelCase` since it's more common in JS/TS world.

We should be clear about why we are using `snake_case` for some contracts and mention this in our docs.

**Comment by idea404** [comment]
I've created [this issue](https://github.com/near/docs/issues/1248) to mention `snake_case` in JS considering standards for docs

**Comment by idea404** [comment]
Mentioned in docs now: https://github.com/near/docs/pull/1290
