### ISSUE TITLE
Dust in attachedDeposit

### ISSUE THREAD

**Issue by lunap2p** [near/near-sdk-js#247]
with attachedDeposit
exam: 5 Near
When I make a function call that gets the amount I attached, I always get a number greater than 5

Why does some dust appear?
2594073385365405696
but if i attach 10 near, this dust number does not appear

I think this is a strange problem
It happens with 5 but not with 10
I tried some other numbers and some numbers come up and some don't
![unknown](https://user-images.githubusercontent.com/89989790/192381104-7da85543-9a0f-4fc0-b692-48aa2228134d.png)
![unknown1](https://user-images.githubusercontent.com/89989790/192381113-1043a7a4-6232-4206-95cf-dfd77d5c1e3e.png)
![unknown2](https://user-images.githubusercontent.com/89989790/192381116-68f12dd5-c601-4725-97de-0fa2a3ea375f.png)

**Comment by ailisp** [comment]
Hi @lunap2p! Very interesting finding! I'm able to reproduce your result with exact number: 5000002594073385365405696. 

> I tried some other numbers and some numbers come up and some don't

Doing a quick try, 1,2,3,4,8,10 NEAR gives exact number, 5,6,7,9 doesn't. I'm investigating where and why it goes wrong

**Comment by lunap2p** [comment]
@ailisp I also tried with some other numbers with decimal value and got the same dust.
I have not found any contact with this number: 2594073385365405696

**Comment by lunap2p** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/89989790/192460830-d9e5dc28-9cd4-41b1-88b9-f4be2c0d3d80.png">

**Comment by ailisp** [comment]
Yes I feel the same, it could be some local uint128 handling bug, that's serious.

**Comment by ailisp** [comment]
Findings so far:

1. workspaces-js attachedDeposit passed correct number to the contract (by check in a equivalent rust contract)
2. C function `u128_to_quickjs`, produce the right result
3. After C function call `attached_deposit((uint64_t)ptr);`, `ptr[1]` is correct, but `ptr[0]` has two incorrect bytes, caused the `2594073385365405696` difference. Still trying to figure out why.

**Comment by ailisp** [comment]
I found the reason, the C function `JS_NewBigUint64` is problematic:
```
return JS_NewBigUint64(ctx, 0x8b0a00a425000000); // lower 8 bytes of 5000000000000000000000000
// Got 0xaf0a00a425000000 ! exactly 2594073385365405696 more than correct.
```

JS_NewBigUint64 is just a wrapper of `bf_set_ui`, so probably `bf_set_ui` is wrong on some numbers

**Comment by ailisp** [comment]
Root cause is indeed `bf_set_ui` from `libbf.c` :(

Minimum repro: adding this test to builder:
```c
void *realloc2(void *opaque, void *ptr, size_t size) {
  return realloc(ptr, size);
}

void test_bf_set_ui() __attribute__((export_name("test_bf_set_ui"))) {
  bf_t a;
  bf_context_t ctx;
  bf_context_init(&ctx, realloc2, NULL);
  bf_init(&ctx, &a);
  bf_set_ui(&a, 0x8b0a00a425000000ul);
  uint64_t ret=0;
  bf_get_uint64(&ret, &a);

  value_return(8, &ret);
}
```
and run it with workspaces-js, `viewRaw`
```
test.only('test_bf_set_ui', async t => {
    const { counter, ali, bob } = t.context.accounts;
    let result = await counter.viewRaw('test_bf_set_ui', {});
    t.is(result, '');
});
```

the number it get become `0xaf0a00a425000000`. cc @volovyks

**Comment by ailisp** [comment]
Debugging `bf_set_ui`, It's likely quickjs is right, but our compiler option / specific #define / wasm runtime configuration went wrong. I tried value_return these things, in `set_bf_ui`:
```
LIMB_BITS - shift // => 32
a0 // => 0x25000000
a0 >> 32 // => 0. It's as expected since a0: uint32_t
a0 >> (LIMB_BITS - shift) // => 0x25000000 (!)
```

**Comment by ailisp** [comment]
@lunap2p Do you have any luck? I did further experiment with build flags and refer to the C standard [C99](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) and [C17](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf), the problem is (for right bitwise shift):

> If the value of the right operand is negative or is greater than or equal to the width of the promoted left operand, the behavior is undefined.

And this is indeed true with current gcc and clang, and even different compiler flags of the same compiler. I tried this:
```c
#define LIMB_BITS 32
#include <stdio.h>
#include <stdint.h>

uint32_t opaque(uint32_t x) {
  return x == 0x3;
}

int main() {
  uint32_t temp = 7;
  uint32_t x = 0x8b0a00a4;
  uint32_t k = LIMB_BITS - opaque(x) * LIMB_BITS;
  temp = temp >> k;
  printf("%d\n", k); // 32
  printf("%d\n", temp); // 7 (!)
  printf("%d\n", temp>>32);
}
```

Compile with `gcc`, `gcc -Os`, `clang` and `clang -Oz` (the last is the flags for compiling near-sdk-js), they gave:
```
~ ./repro-clang
32
7
7
~ ./repro-clangOz
32
7
36180640
~ ./repro-gcc
32
7
7
~ ./repro-gccOs
32
0
0
```

Therefore, it seems a mistake that quickjs developer (and I) assumed `uint32_t >> 32 == 0` - it's actually an undefined behavior, therefore the usage in quickjs `(LIMB_BITS - shift) `, where shift is the number of leading 0s of the higher 32 bit of a uint64, which can be 0, is compiler-dependent and problematic. I'll create an issue there.

For a fix, **a quick try that special case shift == 0 can fix this issue**, but overall, libbf (the bigint library in quickjs) is lacking unit tests, which is a bigger trouble. We need to ensure it's reliable for finanical apps by either thoroughly test / audit by our team, or replace implementation with a more battle-test bigint library.

**Comment by ailisp** [comment]
@lunap2p I made a fix and tests for this specific issue, please have a look: https://github.com/near/near-sdk-js/pull/249. We'll have thorough test in quickjs to ensure it's reliability.
