### ISSUE TITLE
Contract state migration pattern

### ISSUE THREAD

**Issue by petarvujovic98** [near/near-sdk-js#265]
Currently there is no way to prevent the `getState` function call on smart contracts in JavaScript. For our Rust SDK we have the [ignore_state](https://github.com/near/near-sdk-rs/blob/cf25ec2fec72ae9531262250ab8984c7bf7a6d86/near-sdk-macros/src/core_impl/info_extractor/init_attr.rs) `init` attribute.

We should handle this before v1.0 in my opinion.

My initial proposal would be to include an additional parameter to the `call` decorator, as this is the type of function that a migration function would be, and check for the existence of it in the `near-bindgen-exporter` step to see if we should or should not run a `getState` function call for that function.

**Comment by ailisp** [comment]
Yes this will be very helpful. I think your proposal about adding an additional parameter to `call` decorator sounds good

**Comment by vunderkind** [comment]
Hello @ailisp! I'm glad this conversation is happening, and I wrote a small implementation for this (I didn't use call, but the @initialize macro/decorator), with a default "ignoreState: false" hooked into the @NearBindgen. 

But functionally, it does the same thing as @petarvujovic98 suggested — within the near-bindgen-exporter, I have a conditional logic that checks for it being 'true' and it executes the `t.emptyStatement()` if it is, allowing the contract state to be migrated accordingly. 

Is someone already working on this? If yes, I'd like to collaborate with them. Otherwise, I can polish this and submit it as a PR.

[Link to demonstration — it's still imperfect, and requires cleanup.](https://github.com/monopoly-dao/self-upgrade-demo/)

**Comment by vunderkind** [comment]
Checking in regarding this 🙏🏿 @ailisp

(Also congratulations on the new release!)

**Comment by ailisp** [comment]
Hi @vunderkind ! Nice work! I can see your clever design of `@initialize({ignoreState: true})` in `clean_state` and makes `upgrade_self` admin-only. The only addition I would suggest is a `upgrade_state` method, which looks similar in `clean_state`, but it updates state from old format to new format. This and your current version will complete the pattern to fit any real world migration use case.

**Comment by vunderkind** [comment]
Thank you @ailisp! Thank you — and I'll get started on this ASAP.

**Comment by ailisp** [comment]
Hi @vunderkind , hope you are doing well! Do you have time to polish your awesome migration pattern demo (adding a `upgrade_state`)? We'd like to have it in the near-sdk-js 1.0 release, planned for ETH Denver (Feb 24). If not, it's still a great piece of work that will help all near-sdk-js users and we will mention it for in the release.

**Comment by vunderkind** [comment]
Hello Bo, thanks for the nudge!

Yeah, I did forget to continue this, but I can have this shipped to you in
the next 2 days. Does that work?

**Comment by ailisp** [comment]
Thanks @vunderkind ! That will be perfect.

**Comment by volovyks** [comment]
Hey @vunderkind ! Are you planning to continue to work on this issue?
