### ISSUE TITLE
Cross Contract Calls: `near.promiseResult(id)` Error Message Unhelpful

### ISSUE THREAD

**Issue by idea404** [near/near-sdk-js#267]
**Issue**

The SDK currently only informs the caller that extracting a promise result has failed, with no further information from the other account that ran the code yielding the error. Here's an example:

```js
...
    const promise = NearPromise.new(anotherContractId)
      .functionCall("other_contract_function", JSON.stringify({ 
        param1, 
        paranm2,
      }), 0, this.GAS_FEE)
      .then(
        NearPromise.new(near.currentAccountId())
        .functionCall("internalCallbackFunction", JSON.stringify({}), 0, this.GAS_FEE)
      );
    return promise.asReturn();
}
...
```

`internalCallbackFunction` would extact the result as follows: 

```js
  @call({ privateFunction: true })
  internalCallbackFunction() {
    try {
      const promiseResult = near.promiseResult(0);
    } catch (e) {
      near.log("PR ERR", e, e.message, e.stack);
      throw new Error(`Promise result error: ${e.message}`);
    }
...
```

In this case, if the call to `anotherContractId` has failed, we get the following in the logs: 

```bash
Contract logs from escrow.test.near.purchase_in_escrow({"seller_account_id":"bob.test.near","asset_contract_id":"dev-11656.test.near"}) call: [
  'PR ERR {} Promise result Failed     at promiseResult$1 (build/escrow.js:542)\n' +
    '    at internalPurchaseEscrow (build/escrow.js:1347)\n' +
    '    at apply (native)\n' +
    '    at <anonymous> (build/escrow.js:583)\n' +
    '    at internalPurchaseEscrow (build/escrow.js:1510)\n'
]
```

In reality, that call could have failed for a myriad reasons and we are left unaware of them. This current set up forces the developer to always pass an object and avoid throwing errors for calls that will be called by another account program/smart contract. 

**Proposal**
For the error to be passed to the caller such that appropriate logic can be implemented.

**Comment by ailisp** [comment]
Hi @idea404 ! Do you mind to post this in summary on https://near.social/#/devgovgigs.near/widget/IdeasList ? 
There we can submit and discuss possible solutions in near social!

**Comment by ailisp** [comment]
This is unfortunately not possible due to vm function `promise_result` doesn't return data when promise result is failed, only return data when promise result succeed: https://github.com/near/nearcore/blob/e8bda2381b1990fc37e04ca2ecd351963cf9997c/runtime/near-vm-logic/src/logic.rs#L2046

(see the docstring of above function)

Therefore, as a wrapper to `promise_result`, `promiseResult` cannot give error message of the failure reason (e.g. `throw Error("some messagfe")` provided by the callee), isn't available in the caller. 


I think current practice is to design callee in a way that reduce failure cases or let failure reason determined/not important to the caller. If you are sure that promise fail reason has some important use case, we may propose a NEP to core team.
