### ISSUE TITLE
NEAR log does not work in view methods 

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-sdk-js#271]
Community members have reported that `near.log` doesn't work in view methods. No message gets returned which they find to be an issue when it comes to debugging their smart contract

**Comment by nujabes403** [comment]
I think view function can't send log since it's not a transaction.

**Comment by ailisp** [comment]
I just test it and `near.log` works. Logs are only available when you view it with workspace-js `viewRaw`:

To see how it works, modify this test contract:
```
export function test_storage_read() {
  near.log('aaa') // add this line
  near.valueReturn(near.storageRead(bytes("\x00tesdsst\xff")));
}
```
and this test:
```
  let r = await storageApiContract.viewRaw("test_storage_read", "");
  console.log(JSON.stringify(r, null, 2)) // add this line
```

You'll see the log:
```
{
  "block_hash": "24VxvXXz3s7EPJDTT3HdXXDSLuig7KY6rQ3M8CjyUE5M",
  "block_height": 13,
  "logs": [
    "aaa"
  ],
  "result": [
    0,
    1,
    255
  ]
}
```

So it's not a SDK bug. As for thisdalog is not collected and displayed by workspace-js framework, it can be an issue of workspace - we'll fix there.



Update: actually workspace also works, with `view`. @volovyks has made the implementation right. Still repro with above contract, and call with `view` instead of `viewRaw`, running test will log the logs:
```
Contract logs from dev-12770.test.near.test_storage_read("") view call: [ 'aaa' ]
```

So it's not a bug. If you have the developer repro contract, we can look why it's not logging.
