### ISSUE TITLE
When move out of Alpha?

### ISSUE THREAD

**Issue by think-in-universe** [near/near-sdk-js#312]
I think we have added the notice here recently about the Alpha version.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/46699230/204841855-de5b4569-27ba-401f-aa20-453f30466135.png">

What's the timeline of auditing or any other essential steps to move out of Alpha?

This will be important when developers would like to build something serious with JS SDK.

**Comment by volovyks** [comment]
@think-in-universe now we are trying to define the process and requirements for this. I will post updates here once I have them.

**Comment by DavidM-D** [comment]
So there are two streams of work going on to reach 1.0.

The first is API stability, we want to rework the API a bit because some parts are a little finicky to work with and we don't have complete APIs for certain contract interfaces. We're not too far off completing that.

The second string of work is improving the correctness of QuickJS, the library we use to run JS in contracts. We've run into some issues there so we've hired some compiler/interpreter experts to vet and improve it. They're just starting work now, when they're happy with the quality of the code we'll move this into beta. I'll post an estimate on how long that will take after they've gotten stuck into the code.

After that auditors will give the code one more pass and then we can move it from beta to release. This will probably take another 6-8 weeks.

**Comment by think-in-universe** [comment]
@volovyks @DavidM-D Thank you guys! Good to know the plan. 😃 

I have pinged David on Slack about QuickJS auditing last week, and happy to help to connect with some auditors if needed.

**Comment by ailisp** [comment]
@think-in-universe @volovyks @DavidM-D, After reviewing, speaking with a few people and planning, I make the decision to move this project out of alpha stage! See #345

**Comment by ailisp** [comment]
@think-in-universe @volovyks @DavidM-D, After reviewing, speaking with a few people and planning, I make the decision to move this project out of alpha stage! See #345
