### ISSUE TITLE
How to supply gas into cross contract call?

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-sdk-js#70]
Not seeing a way to supply the prepaid gas into a cross contract call anywhere in `near.jsvmCall`. This should be similar to how the RS SDK does it: [https://github.com/near/near-sdk-rs/blob/6555ec593c9185898b7d9d51cf2c884b9e237722/examples/factory-contract/low-level/src/lib.rs](https://github.com/near/near-sdk-rs/blob/6555ec593c9185898b7d9d51cf2c884b9e237722/examples/factory-contract/low-level/src/lib.rs)

Is the enclave doing something different where cross contract calls don't need gas? That would be strange behavior and would feel like it's unintended if someone were to supply a gas amount but not know how much ends up getting used for the cross contract call.

Additionally, if work is needed here, we might need to consider adding the weighted gas API as well or leave some room to add it in the future. cc @austinabell

**Comment by austinabell** [comment]
Well, since the calls happen all within the same call, what would be the need to supply gas? To restrict the amount a call can make? Not sure you can do this from within the runtime anyway.

The only reason we need to specify gas in the Rust SDK is that these transactions happen async and not within the same execution.

**Comment by ChaoticTempest** [comment]
Oh, I didn't realize this happened in the same execution

> To restrict the amount a call can make? Not sure you can do this from within the runtime anyway.

hmm, yeah this would probably require us to have separate APIs for making calls into enclave and non-enclave contracts if we support the latter in the future

**Comment by ailisp** [comment]
@austinabell has addressed 


> To restrict the amount a call can make? Not sure you can do this from within the runtime anyway.

To limit gas in application level, jsvm sync calls you can check `near.prepaidGas()` and `near.usedGas()` to plan for the gas. Say, method1 calls Contract2.method2, method1 can figure out there's still sufficient gas to call method2, otherwise error early, but mostly this isn't necessary - method2 would gas panic any way and no state would be commited.

> hmm, yeah this would probably require us to have separate APIs for making calls into enclave and non-enclave contracts if we support the latter in the future

Yeah, this would be a separate issue

T
