### ISSUE TITLE
Automatic `Object.assign` calls when deserializing collections

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#89]
[https://github.com/near/near-sdk-js/blob/f03eb1a01ee1efbad18a06ab1173edb359e1afdd/examples/status-message/src/status-message-collections.js#L12-L16](https://github.com/near/near-sdk-js/blob/f03eb1a01ee1efbad18a06ab1173edb359e1afdd/examples/status-message/src/status-message-collections.js#L12-L16)

Is an example of the code I'm referring to. I'm wondering why this can't happen within the deserialize function, or if this is documented somewhere?

**Comment by ailisp** [comment]
`super.deserialize` deserialize the state as JSON, the problem is it's an object, say `this.records.keys`, it's like `{"length":3","prefix":"a"}`. But we need it to be a `Vector` class. Manually this is via ` this.records.keys = Object.assign(new Vector, this.records.keys)`

@volovyk-s and I have discussed some way to make this automatic in deserialize, but it is not very easy and not implemented. If you have a good idea to implement that would be cool!

**Comment by austinabell** [comment]
so then can't this issue be kept to track making this simpler and less error-prone for developers?
