### ISSUE TITLE
collections requiring keys and values be serialized to strings

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#91]
This is unintuitive for developers, since it's unclear strings exactly are required without any type indications, but also it's a very limiting API.

Ideally, for functions available, my suggestion (opinionated) is to have low-level functions such as `getRaw`, `pushRaw`, `replaceRaw` along with other core interfaces possibly under another class and then build these high-level APIs on top of that with some convenience such as JSON stringifying keys and values.

The main problem is `string` should not be the key and value type of these structures because it will be too far from the js std library equivalents

**Comment by ailisp** [comment]
Same as #90, strings here are Bytes, and these are actualy `getRaw` `pushRaw`. But the real `get` and `push` etc. like rust-sdk is coupled with the borsh serialization format. We don't have borsh coupled with near-sdk-js and also json deserialize doesn't make sense to every key values, so it seems not clear how to provide a `get`/`push`. Since this, I decide to call `getRaw` etc. just `get`, and let users deal with collections encoding after that.

**Comment by austinabell** [comment]
Why would it not make sense? Wouldn't you want support for non-string/"Bytes" keys?

I just think the API as-is will be misused by people trying to use the `Vector` as an array or the collection maps as a javascript object accepting any value parameter and running into bugs, but maybe we need input from community/other developers for this.

**Comment by ailisp** [comment]
OK. I leave my opinion: arbitrary object seems not intuitive as keys. Because object, if it has reference to other data structure, are typically not used as hash table keys in programming languages.

Arbitrary object can be values, but have a good, extensible interface to support it requires a good design.

**Comment by ailisp** [comment]
@BenKurrek encountered this issue, showing this can be quite common in complex and real world contracts. I still need a good way to implement the get on top of getRaw. For write, `push`/`set`/... can be roughly as `pushRaw/setRaw(JSON.stringify())` (plus some unicode to bytes decoding), but for read, it doesn't know which class is the object and cannot reconstruct the object

**Comment by gagdiez** [comment]
what if the schema (as in https://github.com/near/borsh-js) is set on initialization, and stored in the state as part of the structure?

**Comment by ailisp** [comment]
@gagdiez That's a good idea. However a migration pattern / standard need to be introduced and implemented. Because if user has borsh-js schema S, then make some changes to the schema S'. With schema-included format like JSON, User can write code to handle both version with ease. With borsh, I think we need a deploy-time pattern to:
1. read the old schema
2. deserialize records with old schema, serialize with new schema and store records back
3. replace the schema in state

**Comment by ailisp** [comment]
Addressed in #168
