### ISSUE TITLE
"undefined" instead of undefined

### ISSUE THREAD

**Issue by volovyk-s** [near/near-sdk-js#97]
if value is not available, `jsvmStorageRead()` return s "undefined" (as a string), instead of JS native `undefined`.
It breaks the logic like:
```JS
const res = near.jsvmStorageRead(...)

if (res) { // <-- `true` instead of `false`
// do something
}
```

**Comment by ailisp** [comment]
Hmm I cannot reproduce, I added your snippet to this test:
https://github.com/near/near-sdk-js/compare/repro-97?expand=1

When the key doesn't exist, jsvm.view shows it returns null (this can be different from original near.jsvmStorageRead returns since layers of codegen), and res is falsy (this is certain, ensured by test)

**Comment by volovyk-s** [comment]
This is happening when I have some garbage as a keyPrefix (definitely not a standard situation),
```JS
get(key) {
        near.log(`LookupMap get`);
        near.log(`key: ${key}`);
        let storageKey = this.keyPrefix + key
        near.log(`storageKey: ${storageKey}`);
        const res = near.jsvmStorageRead(storageKey)
        near.log(`res: ${res}`);
        near.log(`typeof res: ${typeof(res)}`);
        return res
    }
```

Gives me:
![image](https://user-images.githubusercontent.com/4030422/172367055-3bfb0588-476b-41bf-aba0-d96cd81053a4.png)

**Comment by volovyk-s** [comment]
Closing this issue for now.
